name: Container
on: push

jobs: 
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:17-alpine3.14
    steps:
      - name:  Log node Version
        run: |
          cat /etc/os-release
          
      